### PR TITLE
update `is-generator-function`

### PR DESCRIPTION
**Pull request by tunnckoCore**
check used in `co@4+`

btw `npm test` not works in iojs@2

### CODE REVIEW

**Comment by blakeembrey** [comment]
Are there any reason for the changes, other than because it's what `co` does?

**Comment by tunnckoCore** [comment]
**plus**
- apply feross/standard (sorry if you dont want it)
- change mocha with `assertit` which is `testit` on steroids - faster and smaller than mocha
- update travis to install and check standard istanbul-harmony and coveralls

**Comment by tunnckoCore** [comment]
> Are there any reason for the changes, other than because it's what co does?

amm.. cuz running tests not works on iojs

**Comment by blakeembrey** [comment]
> amm.. cuz running tests not works on iojs

Did you even look at why? `node: bad option: --harmony-generators` Just remove that option.

**Comment by tunnckoCore** [comment]
Im not trying to force and promote `assertit` but it is so small and easy.

> Did you even look at why?

yea

**Comment by blakeembrey** [comment]
I'm going to close this issue unless there's a reason for the code change, but I will tidy up the code since I use `standard` in my more recent projects. I won't, however, be removing `mocha` and `chai`.

**Pull request closed without merging**
