### PR TITLE
Test + fix for (fake) generator functions

### PR DESCRIPTION
**Pull request by mk-pmb**
I've worked around a minor istanbul/mocha "Transformation error" because I've no idea about their inner workings.

### CODE REVIEW

**Comment by mk-pmb** [comment]
I've no idea about coveralls either, but hold the merge anyways because I'll commit a better fake.

**Comment by blakeembrey** [comment]
@mk-pmb Can you explain what you're trying to do here?

**Comment by blakeembrey** [comment]
@mk-pmb Do you think this is really required? I gather what you're trying to do, but technically it won't work across frames either - something that is currently supported, even if it's accidentally. Any change now would be a breaking change, and I don't really see much value beyond duck typing this. For example, it'll also break if using different transpilers and/or native generators (E.g. one transpiler generated a generator-compat function in a dependency and you're using it in a native generator context).

**Comment by blakeembrey** [comment]
Closing with the issues mentioned above. Duck typing is best for what I'm trying to achieve here. It's pretty much the same situation of promises - you wouldn't detect promises by checking it's an instance of `Promise` because that ignores every promise-compatibility library.

**Pull request closed without merging**
